### ISSUE TITLE
Evaluate if "issues" should be converted into "discussions"

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/meta#16]
## Proposed change

GH has introduced "discussions". For me it looks like just an issue, but under another title. Should we convert the issues into discussions?

Though it should be checked, if it is possible to control discussions templates.

**Comment by theotterlord** [comment]
Discussions are designed for a very different purpose. I believe that issues still serve this in a better way. It could be useful to use discussions as a sort of living Q&A/FAQ, but I don't see them replacing issues for this project
