### ISSUE TITLE
OSII Logo?

### ISSUE THREAD

**Issue by mikaelbr** [open-source-ideas/meta#2]
Should we have an OSII logo to use on avatars and such?

One idea I had was to use the OSI (Open Source Initiative) logo (which is CC licensed) to create a light bulb. 

Any thoughts, @open-source-ideas/osii-maintainers ?

<img width="426" alt="screenshot 2018-08-06 20 18 36" src="https://user-images.githubusercontent.com/606374/43733757-f8f0484e-99b5-11e8-821f-f613399d40d2.png">

(Based on the [Open Source Initiative](https://opensource.org/) logo, not affiliated or endorsed by OSI in any way.)

**Comment by FredrikAugust** [comment]
Well, I'm no designer, but I would vote for option one or two.

**Comment by mikaelbr** [comment]
I think we can tweak the colours some, and maybe increase the sizing some. And it could do in a pinch until something better comes along?

Something like this?

<img width="582" alt="screenshot 2018-08-06 20 27 08" src="https://user-images.githubusercontent.com/606374/43734144-19e94626-99b7-11e8-9fef-17324f04a777.png">

**Comment by FredrikAugust** [comment]
Looks wonderful! :) Good job

**Comment by mikaelbr** [comment]
Reading more it maaay be that this is not OK alterations/use of the logo: https://opensource.org/logo-usage-guidelines and https://opensource.org/logo-usage-guidelines. Will check out some more.

**Comment by mikaelbr** [comment]
It looks like my idea is ruined. I was originally thinking the page and it's content was CC, but didn't see the trademark. So using the "Open Source icon" is a no-go. Shame, I kind of liked the idea. Not as pretty, but what about something like?

<img width="400" alt="screenshot 2018-08-06 21 04 52" src="https://user-images.githubusercontent.com/606374/43736045-9cbe4baa-99bc-11e8-9bf3-24b141e3cf9a.png">

**Comment by FredrikAugust** [comment]
Well, that's a bummer.

Regardless, the last suggestion looks good to me, we good O for open source, light bulb for idea, and it's easy to understand.

**Comment by mikaelbr** [comment]
Updated and added raw files here: https://github.com/open-source-ideas/meta/tree/master/graphics

**Comment by FredrikAugust** [comment]
Looks fabulous! :sparkles:
