### ISSUE TITLE
 Add programming language tags Open Source Ideas Initiative (by @dannycolin)

### ISSUE THREAD

**Issue by mikaelbr** [open-source-ideas/meta#3]
Originally form @dannycolin in https://github.com/open-source-ideas/open-source-ideas/issues/76

---

## Proposed change

Add programming language tags to issues and also show them on the website

## Motivation

This would help people to filter project ideas by programming languages.

## Proposed implementation

- Create a set of tags with the same color that looks like `language : JavaScript`
- Show them on the website. (btw where's the website source code, if we want to help?)

Suggestions, ideas are welcomed.

**Comment by KaKi87** [comment]
up

**Comment by FredrikAugust** [comment]
I'm going to argue for a "no" on this one for the following reasons:

- There is an ungodly amount of programming languages out there; creating a tag for each and every one would take quite a long time
- I don't see why it needs to be specified. Most projects aren't locked to one programming language. If the project is to create a website with a backend; whether that backend is written in RoR/Spring/Flask/Phoenix/etc. doesn't really matter, and should be discussed between the participating members.
- _If_ the project is language-dependant, it should (and in my experience) does say so in the title of the project

**Comment by FredrikAugust** [comment]
> up

You can see a quite lengthy discussion regarding this in the linked issue as well.
