### ISSUE TITLE
Migrate from GitHub (by @KOLANICH) 

### ISSUE THREAD

**Issue by mikaelbr** [open-source-ideas/meta#4]
Originally by @KOLANICH at https://github.com/open-source-ideas/open-source-ideas/issues/67
---

> Consider moving away from GitHub due to the recent (though still open) acquisition by Microsoft and taking into account what Microsoft have made to its own websites (they (at least some of them) don't work at all without JavaScript enabled and have tracking scripts, if M$ done this (or something else unfriendly, like unfriendly shifts in privacy policy) to GitHub, I (and I guess some other self-respecting people) will have to delete my account). Also GH is a de-facto proprietary monopoly, and having monopolies is bad, so I have thought long ago about migrating to GL (which is free software, even though the company running it seems to be unfriendly (the service Gitter owned by that company uses browser fingerprinting), the fact the software is free allows people to fork the software and migrate to own (or third-party) servers), but there are too little devs using it. But now, when the exodus from GH has started, it's a good opportunity to join the movement and make the market a little bit less monopolised.

**Comment by FredrikAugust** [comment]
Closing due to negative feedback on idea.
